### PR TITLE
Release of 1.3.0 bumping darkstyle and qCustomplot and adding new features

### PR DESCRIPTION
**Pull request by Eriobis**

### CODE REVIEW

**Comment by CieNTi** [comment]
Nice to see this! I'll review it thie weekend.

**Comment by Eriobis** [comment]
Any progress on this ?

**Comment by CieNTi** [comment]
Hi and sorry for the delay .. it's merged now :D

**Comment by Eriobis** [comment]
Great ! I'm doint some other stuff right now, but I might add a csv reader to be able to read the saved files in the futur !

**Comment by CieNTi** [comment]
Sounds great, I'm now thinking about to include some kind of CI/CD for auto-builds, what do you think?

**Comment by CieNTi** [comment]
For your records, an issue was raised asking for binaries and I copied yours.

Please review it and tell me if you're fine with it and/or if you want to modify something.

[Link to release, notes and binaries on this repo](https://github.com/CieNTi/serial_port_plotter/releases/tag/v1.3.0)

**Pull request merged**
